config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "lists#index"
  resources :lists, only: [:index, :show, :new, :create, :destroy] do
    resources :bookmarks, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
  resources :reviews, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie, uniqueness: { scope: :list }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :reviews, dependent: :destroy

  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true
  validates :overview, presence: true
  has_many :bookmarks
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    #on va chercher la liste
    # @list = List.find(params[:list_id])
    # on va créer un bookmark
    @bookmark = Bookmark.new(bookmark_params)
    # on associe le bookmark à la liste
    @bookmark.list = @list
    # si on peut sauvegarder le bookmark
    if @bookmark.save
      # on redirige vers la liste
      redirect_to list_path(@list)
      # sinon on affiche le formulaire
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    # on va chercher la liste
    @list = List.find(params[:id])
    # on va chercher le formulaire du new bookmarks de la liste
    @bookmark = Bookmark.new
    # on va chercher le formulaire du new review de la liste
    @review = Review.new(list: @list)
  end

  def new
    @list = List.new
  end

  def create
    # on va créer une liste
    @list = List.new(list_params)
    # si on peut sauvegarder la liste
    if @list.save
      # on redirige vers la liste
      redirect_to list_path(@list)
    else
      # sinon on affiche le formulaire
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    # on va chercher la liste
    @list = List.find(params[:id])
    # on va détruire la liste
    @list.destroy
    # on redirige vers toutes les listes
    redirect_to lists_path(@list), status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  # pas nécessaire -> dans lists_controller
    # def new
    #   @review = Review.new
    # end

  def create
    # on va créer une review
    @review = Review.new(review_params)
    # on va chercher la liste
    @list = List.find(params[:list_id])
    # on associe la review à la liste
    @review.list = @list
    # si on peut sauvegarder la review
    if @review.save
      # on redirige vers la liste
      redirect_to list_path(@list)
    else
      # sinon on affiche la liste
      @bookmark = Bookmark.new
      render 'lists/show', status: :unprocessable_entity
    end
  end

  def destroy
    # on va chercher la review
    @review = Review.find(params[:id])
    # on va détruire la review
    @review.destroy
    # on redirige vers la liste
    redirect_to list_path(@review.list), status: :see_other
  end
end

private

def review_params
  # on va chercher les params de la review
  params.require(:review).permit(:comment, :rating)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/_modal.html.erb
<div class="modal fade" id="new_movie_modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add a movie to your <%= list.name %> list</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
        </button>
      </div>
  <%= simple_form_for [list, bookmark] do |f| %>
        <div class="modal-body">
          <%= f.association :movie, collection: Movie.all.order(:title), prompt: "Select a movie", input_html: { data: { controller: "tom-select" } } %>
          <%= f.input :comment, placeholder: "Enter a comment about the movie" %>
        </div>
        <div class="modal-footer">
          <%= f.submit "Add movie", class: "btn btn-flat" %>
          <button type="button" class="btn btn-cancel" data-bs-dismiss="modal">Back</button>
        </div>
      <% end %>


    </div>
  </div>
</div>

app/views/bookmarks/_modaltest.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Add a movie to your <%= @list.name %> list</h3>
        <%= simple_form_for [list, bookmark] do |f| %>
          <%= f.input :comment, placeholder: 'Enter a comment about the movie' %>
          <%= f.association :movie, prompt: "Select a movie", input_html: {data: { controller: "tom-select"}} %>
          <%= f.submit class: "btn btn-flat" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookmarks/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Add a movie to your <%= @list.name %> list</h3>
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.input :comment, placeholder: 'Enter a comment about the movie' %>
          <%= f.association :movie, prompt: "Select a movie", input_html: {data: { controller: "tom-select"}} %>
          <%= f.submit class: "btn btn-flat" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchListbis</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>
    <script>
        var typed = new Typed(".mov",{
        strings: [, "any kind of movies"] ,
        typeSpeed: 100,
        backSpeed: 100,
        loop: true

        })
    </script>
  </body>
</html>

app/views/lists/index.html.erb
<div class="background-image" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url('https://images.unsplash.com/photo-1577382144834-8a80d92b925c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80')">

<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
    <h1> Save <span class="mov"> </span></h1>
    <h3 class="typed-js" data-controller="typed-js"> </h3>
  </div>
  </div>
  <div class="container py-5">
    <div class="d-flex align-items-center justify-content-between mb-3">
      <h3 class="mb-0 " style="color:white" >My Lists</h3>
      <div class="new-movie" style="color:white" >
        <%= link_to "Create a movie list", new_list_path, class:"text-decoration-none text-white border border-white p-3" %>
            </div>
    </div>
    <div class="row">
      <% @lists.each do |list| %>
        <div class="co-12 col-sm-6 col-md-4 mb-3">
          <%= link_to list_path(list), class:"text-decoration-none" do %>
            <div class="card-category" data-aos="zoom-in" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.photo.attached? ? cl_image_path(list.photo.key) : asset_path('list_background.jpg') %>)" >
              <%= list.name %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Create a new list</h3>
        <%= simple_form_for @list do |f| %>
          <%= f.input :name, placeholder: 'Drama' %>
          <%= f.input :photo, as: :file %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="position-relative">
  <div class="card-category card-large" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @list.photo.attached? ? cl_image_path(@list.photo.key) : asset_path('list_background.jpg') %>)">
    <h1><%= @list.name %></h1>
  </div>
  <span class="movie-tag"><%= pluralize(@list.movies.size, "movie") %></span>
</div>

<div class="container mb-5">
  <div class="d-flex flex-column justify-content-between my-4">
    <span class="mb-2 d-block"><small><em class="text-muted"><%= "You haven't saved any movies yet!" if @list.movies.empty? %></em></small></span>

    <button class="button text-center">
      <%= link_to "Add a bookmark", new_list_bookmark_path(@list), class: "btn"%>
      <div class="button__horizontal"></div>
      <div class="button__vertical"></div>
    </button>
    <div class ="link-btns">
      <%= link_to "Delete this list", list_path(@list), class: "btn", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" } %>
    <%= link_to "Back to all lists", lists_path, class: 'btn'%>
    </div>
  </div>

  <div class="row my-2">
    <% @list.movies.each do |movie| %>
      <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
      <div class="col-12 col-sm-6 mb-4" data-aos="zoom-in">
        <div class="bg-white rounded shadow h-100">
          <%= image_tag movie.poster_url, alt: movie.title, class: "movie-img rounded-top" %>
          <div class="p-3 rounded-bottom d-flex flex-column">
            <strong><%= movie.title %> <span class="text-muted font-weight-normal">• <%= movie.rating.to_f %> <i class="fas fa-star star-yellow"></i></span></strong>
            <small class="text-muted"><%= movie.overview %></small>
            <div class="d-flex align-items-end justify-content-between pt-4">
              <div>
                <i class="fas fa-quote-left me-2"></i><small class="flex-grow-1"><%= bookmark.comment %></small>
              </div>
               <%=link_to bookmark_path(bookmark), style:"text-decoration:none;color:black;text-align:center",
                    data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{movie.title} from your #{@list.name} list"} do %>
                   <i class="fa-regular fa-trash-can"></i>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="row">
    <div class="col-12 col-sm-6">
      <h3>Reviews</h3>
      <% if @list.reviews.empty? %>
        <small><em class="text-muted">Be the first one to review this list</em></small>
      <% end %>
      <% @list.reviews.each do |review| %>
        <div>
          <% review.rating.times do %>
            <i class="fas fa-star star-yellow"></i>
          <% end %>
          <small><em class="text-muted"><%= distance_of_time_in_words_to_now(review.created_at) %> ago</em></small>
          <p class="mb-0"><%= review.comment %></p>
        </div>
        <hr>
      <% end %>
    </div>
  </div>

    <div class="col-12 col-sm-6">
      <div class="bg-white rounded p-3">
        <h5>Add your review</h5>
        <%# <%= link_to "Add a review", new_list_review_path(@list), class: "btn"%>
        <%= simple_form_for [@list, @review] do |f| %>
          <%= f.input :comment, placeholder: "Add your review here..." %>
          <%= f.input :rating, as: :select, collection: (1..5), required: true, prompt: "What's your rating", input_html: { data: { controller: "star-rating" } } %>
          <%= f.submit class:"btn btn-flat" %>
        <% end %>
      </div>
    </div>

</div>

app/views/reviews/new.html.erb
<div class="col-12 col-sm-6">
  <div class="bg-white rounded p-3">
    <h5>Add your review</h5>
    <%= simple_form_for [@list, @review] do |f| %>
      <%= f.input :comment, placeholder: "Add your review here..." %>
      <%= f.input :rating, as: :select, collection: (1..5), required: true, prompt: "What's your rating", input_html: { data: { controller: "star-rating" } } %>
      <%= f.submit class:"btn btn-flat" %>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class = "navbar navbar-expand-sm navbar-light navbar-lewagon px-3">
  <%= link_to root_path do %>
    <%= image_tag "popcorn.png", alt: "alttext", class: "logo", style: "height: 60px"%>
  <% end %>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto">
      <li class="nav-item active">
        <%= link_to "My lists", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "New list", new_list_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</div>